name: Cronjob Workflow (get and submit prices to server)

on:
  workflow_dispatch:  # this is needed eventhough we are not doing the manuall run. however, for some reason, the cronjob will fail if we comment this line!
  schedule:
    - cron: '0,15,45 4-20 * * *'  # Run every 15 minutes
  # push:
  #   branches:
  #     - main
  #     - development

jobs:
  cronjob:
    name: Run tests and then post prices
    runs-on: ubuntu-latest

    # services:
    #   redis:
    #     image: redis:6.0-alpine
    #     ports:
    #       - 6379:6379
    #     options: --name redis-cache

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
  
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9.19
      
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      # - name: Run unittest
      #   env:
      #     REDIS_HOST: "localhost"
      #     REDIS_PORT: "6379"
      #     REDIS_PASSWORD: ""
      #     SECRET_KEY: ${{ secrets.SECRET_KEY }}
      #   run: |
      #     python -m unittest discover tests

      - name: Install Proxy
        run: |
          sudo snap install opera-proxy
          opera-proxy -country EU >/dev/null 2>&1 &
          sleep 10 

      - name: Post prices to backend
        if: success()
        env:
          NERKH_TOKEN: ${{ secrets.NERKH_TOKEN }}
        run: |
          export http_proxy="http://127.0.0.1:18080"
          export https_proxy="http://127.0.0.1:18080"
          python data_submitter/main.py
